spring:
  config:
    import: 'consul:'
  application:
    name: auth-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: auth-service-i1
#        Удалить когда буду все собирать в докер
        hostname: 192.168.0.103
        acl-token: 527e2915-295d-bfb0-277a-87fc893e3983
      config:
        format: yaml
        data-key: data
        acl-token: e34f5694-2d34-3703-32b9-f262ff82eac8
# Вынести в сервер конфигурации
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
app:
  topics:
    email-verification:
      name: user.email-verification
      partitions: 1
      replicas: 1









