spring:
  config:
    import:
      - 'optional:consul:'
      - 'classpath:application-backup.yaml'
  application:
    name: auth-service
  cloud:
    consul:
      port: 8500
      host: consul-server
      discovery:
        instance-id: auth-service-i1
      config:
        format: yaml
        data-key: data
        fail-fast: true