spring:
  config:
    import: 'consul:'
  application:
    name: auth-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: auth-service-i1
#        Удалить когда буду все собирать в докер
        hostname: 192.168.0.103
        acl-token: 527e2915-295d-bfb0-277a-87fc893e3983
      config:
        format: yaml
        data-key: data
        acl-token: e34f5694-2d34-3703-32b9-f262ff82eac8
  datasource:
    url: jdbc:postgresql://localhost:15432/auth_db
    username: auth_user
    password: auth

  data:
    redis:
      host: localhost
      port: 6379
      password: werpipl15
      database: 0
  cache:
    type: redis

  flyway:
    enabled: true
    locations: classpath:db/migration
