spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: werpipl15
      database: 0
  cache:
    type: redis
    redis:
      cache-null-values: false
  rabbitmq:
    host: localhost
    port: 5672
    username: auth_user
    password: authentification
    virtual-host: notification_vhost

rabbitQueue:
  registerEvent: registration.event

server:
  port: 9191