spring:
  application:
    name: auth-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: auth-service-i1
#        Удалить когда буду все собирать в докер
        hostname: 192.168.0.103
        acl-token: 527e2915-295d-bfb0-277a-87fc893e3983

  datasource:
    url: jdbc:postgresql://localhost:15432/auth_db
    username: auth_user
    password: auth

  data:
    redis:
      host: localhost
      port: 6379
      password: werpipl15
      database: 0

  cache:
    type: redis

  kafka:
    consumer:
      group-id: auth-group
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.lfey.authservice.dto.kafka"
        spring.json.use.type.headers: false
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  topics:
    email-verification:
      name: user.email-verification
      partitions: 3
      replicas: 1

jwt:
  access:
    expiration: 3600000
  refresh:
    expiration: 1209600000