spring:
  config:
    import: 'consul:'
  application:
    name: notification-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: notification-service
        hostname: 192.168.0.103
        acl-token: bf8d1bb3-5be0-8690-e474-fe408732b426
      config:
        format: yaml
        data-key: data
        acl-token: bf8d1bb3-5be0-8690-e474-fe408732b426