services:
  redis:
    hostname: redis
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=werpipl15 # Опционально, для аутентификации
    command:
      - redis-server
      - --requirepass werpipl15 # Активируем аутентификацию
      - --appendonly yes # Включить persistence

  kafka-1:
    image: bitnami/kafka:latest
    ports:
      - "9090:9090"  # PLAINTEXT
      - "9091:9091"  # CONTROLLER
      - "9092:9092"  # EXTERNAL
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=bf31a58b90557d0dfdbacb0c
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9090,EXTERNAL://kafka-1:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    networks:
      - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9090  # Используйте внутренний порт
      - KAFKA_CLUSTERS_0_ZOOKEEPER=null
    depends_on:
      - kafka-1
    networks:
      - kafka-network

  consul-server:
    image: consul:1.15.4
    container_name: consul-server
    hostname: consul-server
    ports:
      - "8500:8500"  # Порт для доступа к Consul UI
    volumes:
      - consul-data:/consul/data
      - ../config/agent.json:/consul/config/agent.json
    command: >
      agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
      -config-dir=/consul/config
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "server":true, "enable_script_checks":true}
    networks:
      - consul-network
  consul-client:
    image: consul:1.15.4
    container_name: consul-client
    hostname: consul-client
    depends_on:
      - consul-server
    volumes:
      - ../config/agent.json:/consul/config/agent.json
    command: >
      agent -client=0.0.0.0 -retry-join=consul-server
      -config-dir=/consul/config
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "server":false}
    networks:
      - consul-network

networks:
  kafka-network:
    driver: bridge
  consul-network:
    driver: bridge

volumes:
  redis_data:
  consul-data:
