services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ../config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ../config/definitions.json:/etc/rabbitmq/definitions.json:ro
    environment:
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq
      RABBITMQ_ERLANG_COOKIE: "SECRET_COOKIE"
  redis:
    hostname: redis
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=werpipl15 # Опционально, для аутентификации
    command:
      - redis-server
      - --requirepass werpipl15 # Активируем аутентификацию
      - --appendonly yes # Включить persistence
  consul-server:
    image: consul:1.15.4
    container_name: consul-server
    hostname: consul-server
    ports:
      - "8500:8500"  # Порт для доступа к Consul UI
    volumes:
      - consul-data:/consul/data
      - ../config/agent.json:/consul/config/agent.json
    command: >
      agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
      -config-dir=/consul/config
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "server":true, "enable_script_checks":true}
    networks:
      - consul-network
  consul-client:
    image: consul:1.15.4
    container_name: consul-client
    hostname: consul-client
    depends_on:
      - consul-server
    volumes:
      - ../config/agent.json:/consul/config/agent.json
    command: >
      agent -client=0.0.0.0 -retry-join=consul-server
      -config-dir=/consul/config
    environment:
      - CONSUL_LOCAL_CONFIG={"datacenter":"dc1", "server":false}
    networks:
      - consul-network
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - keycloak_network
networks:
  keycloak_network:
  consul-network:
    driver: bridge
volumes:
  redis_data:
  consul-data:
  postgres_data:
