spring:
  config:
    import: 'consul:'
  application:
    name: booking-service
  cloud:
    consul:
      port: 8500
      host: localhost
      config:
        format: yaml
        data-key: data
        acl-token: 66b41fb4-766f-66f4-d4b7-42d0295fe586



