spring:
  config:
    import:
      - 'optional:consul:'
      - 'classpath:application-backup.yaml'
  application:
    name: booking-service
  cloud:
    consul:
      port: 8500
      host: localhost
      config:
        format: yaml
        data-key: data
  flyway:
    locations: classpath:db/migration

  data:
    redis:
      password: werpipl15
      host: localhost
      port: 6379
      database: 2
  cache:
    type: redis
    redis:
      time-to-live: 1800000

app:
  topics:
    hotel-booking-event:
      name: hotel.booking-event
      partition: 1
      replicas: 1


