spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:35432/booking_db
    username: booking
    password: booking
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      acks: all
      properties:
        retry:
          backoff:
            ms: 1000
        delivery:
          timeout:
            ms: 60000
        linger:
          ms: 0
        request:
          timeout:
            ms: 30000
        enable:
          idempotence: true
        spring.json.trusted.packages: "com.lfey.statygo.dto.BookingDetailsEvent"
  data:
    redis:
      password: werpipl15
      host: localhost
      port: 6379
      database: 2
  cache:
    type: redis
    redis:
      time-to-live: 1800000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  store:
    path: /home/another/Project/developering/stay-go/photo
  topics:
    hotel-booking-event:
      name: hotel.booking-event
      partition: 1
      replicas: 1
server:
  port: 9393
logging:
  level:
    org:
      hibernate:
        SQL: debug


