spring:
  application:
    name: stay-go
  datasource:
    url: jdbc:mariadb://localhost:3306/stay_go
    username: app_user
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: werpipl15
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: werpipl15
logging:
  level:
    org:
      hibernate: info
      springframework:
        jdbc: info
        security: debug
    root: info
  file:
    name: createTable.log
server:
  port: 8080

staygo:
  email:
    host: smtp.yandex.com
    username: AnotherSc@yandex.ru
    port: 465
    password: cufzeqevxzjpwozi
