spring:
  application:
    name: stay-go
  datasource:
    url: jdbc:mysql://localhost:3306/stay_go
    username: root
    password: werpipl15
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: root
      password: werpipl15
logging:
  level:
    org:
      hibernate: info
      springframework:
        jdbc: info
    root: info
  file:
    name: createTable.log

staygo:
  email:
    host: smtp.yandex.com
    username: AnotherSc@yandex.ru
    port: 465
    password: cufzeqevxzjpwozi
