spring:
  application:
    name: user-service
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        instance-id: user-service-i2
#       Delete by deploy
        hostname: 192.168.0.103
        acl-token: 86e8c5ba-634e-00f7-ce65-add819cbc387
  datasource:
    url: jdbc:postgresql://localhost:25432/user_db
    username: user_user
    password: user
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: werpipl15
      database: 1
  cache:
    type: redis
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
server:
  servlet:
    context-path: /user-service
  port: 9292
