services:
  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user
    ports:
      - "15432:5432"
volumes:
  postgres_data: